### ISSUE TITLE
Mouse not working properly

### ISSUE THREAD

**Issue by ImCrus** [Vwing/daggerfall-unity-1#2]
Testing on Mi Pad 5, HyperOs, Android 14.
I installed and was in the tutorial trying the game and when i turned with my mouse i noticed the mouse reached the borders, so i can see the mouse isn't "locked" in the game, so while i can turn properly, the mouse then reaches the border making it complicated to play it like it :')
Thank you for your time and amazing work btw!

Edit: A quick video to show the problem! Had to be quick because of the size... However i hope you can understand it.

https://github.com/Vwing/daggerfall-unity-android/assets/172995026/fed18f1a-b4ef-4eb7-b4db-f4ee593483e7

**Comment by Vwing** [comment]
Thanks for submitting this bug report. This is a known issue, see #1
